version: '3.7'
services:
  app:
    build: .
    volumes:
      - ./microservice:/app/microservice
  web:
    image: nginx:alpine
    volumes:
      - ./microservice:/app/microservice
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
